spring:
  datasource:
    password: NF0jVnKzmSaURvBVAPTLm6g5qrbJOeP2
    url: jdbc:postgresql://dpg-cruicqjtq21c738jba30-a:5432/dbtaskmanager_oi7f?password=NF0jVnKzmSaURvBVAPTLm6g5qrbJOeP2&user=dbtaskmanager_oi7f_user
    username: dbtaskmanager_oi7f_user