spring:
  datasource:
    password: ORqFjIYBdeVO8JVdBGgAs2kkJH9mGqpx
    url: jdbc:postgresql://dpg-cr9iqo8gph6c73d0jpp0-a:5432/db_evpj?password=ORqFjIYBdeVO8JVdBGgAs2kkJH9mGqpx&user=db_evpj_user
    username: db_evpj_user